- name: Register demo
  hosts: localhost
  tasks:
    - name: Rum uptime command
      ansible.builtin.shell: uptime
      register: out

    - name: Print shell output
      ansible.builtin.debug:
        msg: "{{ out }}"

    - name: Rum LS command
      ansible.builtin.shell: ls
      register: ls_out

    - name: Print shell LS output
      ansible.builtin.debug:
        msg: "{{ ls_out }}"