- name: Filter demo
  hosts: localhost
  vars:
    URL: https://nginx.org/download/nginx-1.22.1.zip
  tasks:
    - name: Download nginx zip
      ansible.builtin.unarchive:
        src: "{{ URL }}"
        dest: /tmp/
        remote_src: yes

    - name: Print Host machine information
      ansible.builtin.debug:
        msg: "{{ URL | split('/') }}"
