- name: Filter demo
  hosts: localhost
  vars:
    URL: https://nginx.org/download/nginx-1.25.3.zip
  tasks:
    - name: Download nginx zip
      ansible.builtin.unarchive:
        src: https://nginx.org/download/nginx-1.22.1.zip
        dest: /tmp/
        remote_Src: yes
        register: out
      ignore_errors: yes

    - name: Print Host machine information
      ansible.builtin.debug:
        msg: "{{ out }}"
